trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6 (the minimum supported)'
  inputs:
    versionSpec: '3.6'

- script: |
    python -m pip install --upgrade pip setuptools
    pip install wheel twine
  displayName: 'Install build tools'

- script: python setup.py sdist bdist_wheel
  displayName: 'Build source distribution and wheel'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'CimbolicReleases'

- script: twine upload -r CimbolicReleases --config-file $(PYPIRC_PATH) dist/*
  displayName: 'Publish the packages'
  