# Generated by Django 2.2.5 on 2019-09-09 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the variable (eg: BASIC)', max_length=80)),
                ('description', models.TextField(blank=True, help_text='A brief description of the variable', max_length=500)),
                ('type', models.CharField(choices=[('sys', 'system-defined'), ('usr', 'user-defined')], help_text='Whether the variable is system defined or user-created', max_length=3)),
                ('source_model', models.CharField(blank=True, help_text='The model to which this variable belongs (eg: payroll.Component)', max_length=500, validators=[django.core.validators.RegexValidator('^\\w+\\.\\w+$')])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the variable is currently active')),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(default='NULL', help_text='Cimbolic condition for the rule to be set')),
                ('rule', models.TextField(help_text='Cimbolic arithmetic rule to be set')),
                ('priority', models.PositiveIntegerField(help_text='Set the ordering of condition-checking (1 is highest)', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the formula is currently active')),
                ('variable', models.ForeignKey(help_text='Variable to which this formula is bound', on_delete=django.db.models.deletion.CASCADE, related_name='formulae', related_query_name='formula', to='cimbolic.Variable')),
            ],
            options={
                'verbose_name_plural': 'formulae',
            },
        ),
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(fields=('variable', 'priority'), name='unique_formula_priority_per_variable'),
        ),
    ]
