# Generated by Django 2.2.5 on 2019-09-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimbolic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(help_text='Name of the variable (eg: BASIC)', max_length=80, unique=True),
        ),
    ]
