# Generated by Django 2.2.5 on 2019-09-10 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimbolic', '0003_auto_20190909_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='priority',
            field=models.PositiveIntegerField(help_text="Set the ordering of condition-checking (1 is highest) (Note: the priority of a 'NULL' condition will automatically be set to be the lowest)", validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
