# Generated by Django 2.2.5 on 2019-09-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cimbolic', '0004_auto_20190910_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='is_active',
        ),
    ]
