# Generated by Django 2.2.5 on 2019-09-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimbolic', '0005_remove_formula_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='condition',
            field=models.CharField(default='NULL', help_text='Cimbolic condition for the rule to be set', max_length=1000),
        ),
        migrations.AlterField(
            model_name='formula',
            name='rule',
            field=models.CharField(help_text='Cimbolic arithmetic rule to be set', max_length=1000),
        ),
    ]
