# Generated by Django 2.2.5 on 2019-10-07 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimbolic', '0005_remove_formula_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='source_model',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='type',
        ),
        migrations.AddField(
            model_name='variable',
            name='related_data_path',
            field=models.CharField(blank=True, help_text='The dotted path to the data to which this variable is related, in the format {app_label}.{model_name}[.{field_name|pk}]', max_length=500, validators=[django.core.validators.RegexValidator('^\\w+\\.\\w+(\\.\\w+)?$', "Must conform to the regex '^\\w+\\.\\w+(\\.\\w+)?$'")]),
        ),
        migrations.AddField(
            model_name='variable',
            name='related_data_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('M', 'Model'), ('F', 'Model field'), ('I', 'Model instance')], help_text='The type of the data this variable is related to (eg: model, instance)', max_length=1),
        ),
        migrations.AddField(
            model_name='variable',
            name='source',
            field=models.CharField(choices=[('S', 'System'), ('U', 'User')], default='', help_text='Whose action the variable originates from (eg: system, user)', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(help_text='Name of the variable (eg: BASIC, WH_1)', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z_][a-zA-Z0-9_]*$', "Must conform to the regex '^[a-zA-Z_][a-zA-Z0-9_]*$'")]),
        ),
    ]
