# Generated by Django 2.2.5 on 2019-09-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimbolic', '0006_auto_20190924_1449'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(fields=('variable', 'condition'), name='unique_formula_condition_per_variable'),
        ),
    ]
