# Generated by Django 2.2.5 on 2019-10-07 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimbolic', '0006_auto_20191007_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='priority',
            field=models.PositiveIntegerField(help_text="Set the priority of condition-checking (1 is highest) (Note: the priority of a 'NULL' condition will automatically be set to be the lowest)", validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
