# Generated by Django 2.2.5 on 2019-10-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cimbolic', '0007_auto_20191007_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Whether the variable is currently active'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='source',
            field=models.CharField(blank=True, choices=[('S', 'System'), ('U', 'User')], default='U', help_text='Whose action the variable originates from (eg: system, user)', max_length=1),
        ),
    ]
